const fs = require('fs');
let c = fs.readFileSync('C:/Projects/riskpro/frontend/src/data/machines.ts', 'utf8');

function insertAfterById(id, newContent) {
  const idx = c.indexOf(`id: '${id}'`);
  if (idx === -1) { console.log(`${id} NOT found`); return false; }
  const endIdx = c.indexOf('},', idx) + 2;
  c = c.slice(0, endIdx) + newContent + c.slice(endIdx);
  console.log(`Inserted after ${id}`);
  return true;
}

// ===== ROBOT-COBOT: add co05-co18 after co04 =====
insertAfterById('co04', `
      { id: 'co05', element: 'Ocena biomechaniczna \u2014 brak analizy ISO/TS 15066', threat: 'Przekroczenie dopuszczalnych si\u0142 kontaktu z operatorem', effect: 'Urazy mi\u0119\u015bniowo-szkieletowe, z\u0142amania', defaultS: 3, defaultP: 3, actions: ['Ocena biomechaniczna wg ISO/TS 15066 Tab. A.2', 'Pomiar si\u0142 kontaktu czujnikiem', 'Certyfikacja PFL przez producenta cobota'] },
      { id: 'co06', element: 'Ostre kraw\u0119dzie detalu w chwytaku', threat: 'Przebicie sk\u00f3ry przy kontakcie z detalem w chwytaku', effect: 'Rany k\u0142ute, zak\u0105\u017cenie', defaultS: 3, defaultP: 3, actions: ['Zabezpieczenie ostrych kraw\u0119dzi detali', 'Ocena ryzyka kontaktu z detalem', 'Chwytak z os\u0142onami na kraw\u0119dziach'] },
      { id: 'co07', element: 'Praca cobota w pobli\u017cu maszyn wiruj\u0105cych', threat: 'Kolizja ramienia cobota z s\u0105siedni\u0105 maszyn\u0105', effect: 'Uszkodzenie maszyny, urazy operator\u00f3w', defaultS: 3, defaultP: 2, actions: ['Strefa pracy cobota ograniczona programowo', 'Fizyczne ograniczniki zakresu ruchu', 'Analiza zagro\u017ce\u0144 wsp\u00f3\u0142dzielonej przestrzeni'] },
      { id: 'co08', element: 'Awaria czujnik\u00f3w si\u0142y / momentu', threat: 'Brak detekcji si\u0142y kontaktu przy awarii czujnika', effect: 'Urazy operatora', defaultS: 4, defaultP: 1, actions: ['Diagnostyka czujnik\u00f3w przy ka\u017cdym uruchomieniu', 'Redundantne czujniki si\u0142y', 'Procedura post\u0119powania przy b\u0142\u0119dzie czujnika'] },
      { id: 'co09', element: 'Transport / instalacja cobota', threat: 'Upadek cobota podczas monta\u017cu', effect: 'Zgniecenie os\u00f3b, uszkodzenie cobota', defaultS: 3, defaultP: 2, actions: ['Plan transportu wg DTR', 'Kotwienie podstawy do pod\u0142ogi', 'Min. 2 osoby przy monta\u017cu'] },
      { id: 'co10', element: 'Programowanie cobota (hand guiding)', threat: 'Niezamierzone uruchomienie pe\u0142n\u0105 pr\u0119dko\u015bci\u0105', effect: 'Uderzenie programisty', defaultS: 3, defaultP: 2, actions: ['Tryb hand guiding \u2264 250 mm/s', 'Potwierdzenie operatora przed uruchomieniem', 'Szkolenie z obs\u0142ugi cobota'] },
      { id: 'co11', element: 'Aplikacja spawania / klejenia z cobotem', threat: 'Wdychanie opar\u00f3w przy aplikacjach procesowych', effect: 'Zatrucie, choroby dr\u00f3g oddechowych', defaultS: 3, defaultP: 3, actions: ['Wentylacja wyci\u0105gowa', 'SDS substancji', 'Monitoring TVOCs'] },
      { id: 'co12', element: 'Demonta\u017c cobota', threat: 'Upadek ramienia przy demonta\u017cu', effect: 'Urazy r\u0105k i n\u00f3g', defaultS: 3, defaultP: 1, actions: ['LOTO przed demonta\u017cem', 'Podpora mechaniczna ramienia', 'Min. 2 osoby przy demonta\u017cu'] },`);

// ===== CONVEYOR-BELT: add cb07-cb20 after cb06 =====
insertAfterById('cb06', `
      { id: 'cb07', element: 'Transport / instalacja przenośnika', threat: 'Upadek element\u00f3w przenośnika podczas monta\u017cu', effect: 'Zgniecenie os\u00f3b', defaultS: 3, defaultP: 2, actions: ['Plan monta\u017cu zatwierdzony przez in\u017cyniera', 'Podesty monta\u017cowe certyfikowane', 'Strefa wy\u0142\u0105czona podczas monta\u017cu'] },
      { id: 'cb08', element: 'Pierwsze uruchomienie przenośnika', threat: 'Niezamierzone uruchomienie przy obecno\u015bci os\u00f3b na trasie', effect: 'Urazy od ta\u015bmy w ruchu', defaultS: 3, defaultP: 2, actions: ['Sprawdzenie trasy przed uruchomieniem', 'Sygna\u0142 d\u017awi\u0119kowy 5s przed startem', 'Protok\u00f3\u0142 pierwszego uruchomienia'] },
      { id: 'cb09', element: 'Strefa za\u0142adunku \u2014 r\u0119czne k\u0142adzenie materia\u0142u', threat: 'Pochwycenie r\u0105k przy k\u0142adzeniu na ta\u015bm\u0119', effect: 'Wci\u0105gni\u0119cie r\u0105k mi\u0119dzy ta\u015bm\u0105 a b\u0119bnem', defaultS: 4, defaultP: 3, actions: ['Os\u0142ona strefy za\u0142adunku', 'Kurtyna \u015bwietlna przy pod\u0105waniu r\u0119cznym', 'Szkolenie operatora', 'Prowadnice / lejki kieruj\u0105ce materia\u0142'] },
      { id: 'cb10', element: 'Naprawa ta\u015bmy w ruchu', threat: 'Pochwycenie r\u0105k przy naprawie ta\u015bmy w ruchu', effect: 'Wci\u0105gni\u0119cie ko\u0144czyny', defaultS: 4, defaultP: 2, actions: ['LOTO obowi\u0105zkowe przed napraw\u0105', 'Zakaz naprawy ta\u015bmy w ruchu', 'Procedura zatrzymania awaryjnego'] },
      { id: 'cb11', element: 'Upadek z przenośnika przy serwisie na wysoko\u015bci', threat: 'Upadek serwisanta z wysokiego przenośnika', effect: 'Ci\u0119\u017ckie urazy \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 2, actions: ['Szelki EN 361 przy pracy > 1 m', 'Barierki EN 13374 na pomo\u015bcie', 'Procedura pracy na wysoko\u015bci', 'Zakaz pracy bez asekuracji'] },
      { id: 'cb12', element: 'Zanik zasilania przenośnika', threat: 'Niekontrolowane zsuni\u0119cie si\u0119 materia\u0142u', effect: 'Urazy od zsuwaj\u0105cego si\u0119 \u0142adunku', defaultS: 3, defaultP: 2, actions: ['Hamulec bezpiecze\u0144stwa na nachylonych przenośnikach', 'Procedura post\u0119powania przy zaniku', 'Strefa bezpiecze\u0144stwa przy ko\u0144cu ta\u015bmy'] },
      { id: 'cb13', element: 'Awaria linki zatrzymania awaryjnego', threat: 'Brak mo\u017cliwo\u015bci awaryjnego zatrzymania', effect: 'Urazy bez mo\u017cliwo\u015bci reakcji', defaultS: 4, defaultP: 1, actions: ['Test linki przed ka\u017cd\u0105 zmian\u0105', 'Kontrola napi\u0119cia linki', 'Wymiana linki wg harmonogramu'] },
      { id: 'cb14', element: 'Czyszczenie przenośnika', threat: 'Pochwycenie przy czyszczeniu b\u0119bn\u00f3w / kr\u0105\u017cnik\u00f3w', effect: 'Wci\u0105gni\u0119cie r\u0105k', defaultS: 4, defaultP: 2, actions: ['LOTO obowi\u0105zkowe przed czyszczeniem', 'Skrobaki automatyczne (belt cleaners)', 'Narz\u0119dzia do czyszczenia (nie r\u0119ce)'] },
      { id: 'cb15', element: 'Demonta\u017c przenośnika', threat: 'Upadek element\u00f3w przenośnika', effect: 'Urazy, zgniecenie', defaultS: 3, defaultP: 1, actions: ['Plan demonta\u017cu zatwierdzony', 'Od\u0142\u0105czenie wszystkich medi\u00f3w', 'Strefa wy\u0142\u0105czona'] },`);

// ===== FORKLIFT: add f07-f20 after f06 =====
insertAfterById('f06', `
      { id: 'f07', element: 'Wjazd w\u00f3zka na ramp\u0119 / dok', threat: 'Zje\u017cchanie w\u00f3zka z rampy', effect: 'Wywrotka \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 2, actions: ['Blokada ko\u0142 pojazdu dostawczego (chock)', 'Blokada rampy \u2014 kontrola doku', 'Prze\u015bwit rampy wg DTR w\u00f3zka', 'Szkolenie z pracy na rampie'] },
      { id: 'f08', element: 'Jazda z uniesionym \u0142adunkiem', threat: 'Utrata stateczno\u015bci przy je\u017adzie z uniesionym \u0142adunkiem', effect: 'Wywrotka w\u00f3zka \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 3, actions: ['Zakaz jazdy z \u0142adunkiem powy\u017cej 300 mm', 'Szkolenie operator\u00f3w', 'System monitorowania wysoko\u015bci masztu (opcja)'] },
      { id: 'f09', element: 'Praca na nierównej nawierzchni', threat: 'Wywrotka w\u00f3zka na wybojach / kraweżnikach', effect: 'Przygniecenie operatora', defaultS: 4, defaultP: 2, actions: ['ROPS (Roll Over Protection)', 'Pas bezpiecze\u0144stwa', 'Ocena nawierzchni przed prac\u0105', 'Zakaz wychylania si\u0119 przy wywrotce'] },
      { id: 'f10', element: 'Pr\u0119dko\u015b\u0107 w\u00f3zka w strefach pieszych', threat: 'Potr\u0105cenie pieszego przez szybko jad\u0105cy w\u00f3zek', effect: 'Zmiażdżenie \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 3, actions: ['Ogranicznik pr\u0119dko\u015bci elektroniczny (max 5 km/h)', 'Fizyczne bariery stref pieszych', 'System ostrzegania pieszych (d\u017awi\u0119k, lampa)'] },
      { id: 'f11', element: '\u0141adowanie baterii (w\u00f3zek elektryczny)', threat: 'Wydzielanie wodoru podczas \u0142adowania', effect: 'Wybuch przy iskrze', defaultS: 4, defaultP: 2, actions: ['Strefa \u0142adowania wydzielona z wentylacj\u0105', 'Zakaz palenia i iskrzenia w strefie', 'Detektor wodoru przy \u0142adowarce'] },
      { id: 'f12', element: 'Serwis w\u00f3zka \u2014 uniesione wid\u0142y', threat: 'Opadni\u0119cie wid\u0142y przy serwisie', effect: 'Zmiażdżenie serwisanta', defaultS: 4, defaultP: 2, actions: ['Bezpiecznik mechaniczny wid\u0142y (podpora)', 'LOTO przed serwisem hydrauliki', 'Zakaz pracy pod wid\u0142ami bez podpory'] },
      { id: 'f13', element: 'Kolektor przetw\u00f3rnicy g\u00f0zowej (LP\u0141)', threat: 'Wyciek gazu LP\u0141 \u2014 zagro\u017cenie po\u017carem', effect: 'Po\u017car, wybuch, zatrucie', defaultS: 4, defaultP: 2, actions: ['Kontrola szczelno\u015bci instalacji LP\u0141 co 6 mies.', 'Certyfikowane zbiorniki LP\u0141', 'Detektor gazu w strefie pracy', 'Zakaz u\u017cywania w zamkni\u0119tych halach'] },
      { id: 'f14', element: 'Jazda ty\u0142em \u2014 ograniczona widoczno\u015b\u0107', threat: 'Potr\u0105cenie pieszego przy je\u017adzie ty\u0142em', effect: 'Ci\u0119\u017ckie urazy \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 3, actions: ['Kamera cofania z monitorem', 'Radar / ultrad\u017cwi\u0119k wykrywania pieszych', 'Sygna\u0142 d\u017awi\u0119kowy cofania', 'Szkolenie z jazdy ty\u0142em'] },
      { id: 'f15', element: 'Ergonomia operatora', threat: 'Wibracje ca\u0142ego cia\u0142a przy je\u017adzie', effect: 'Choroby kr\u0119gos\u0142upa', defaultS: 2, defaultP: 3, actions: ['Siedzenie amortyzuj\u0105ce wibracje EN 13490', 'Pomiar A(8) < 0,5 m/s\u00b2', 'Rotacja operator\u00f3w'] },`);

// ===== PACKAGING-FLOW: add pf08-pf20 after pf07 =====
insertAfterById('pf07', `
      { id: 'pf08', element: 'Transport / instalacja maszyny pakuj\u0105cej', threat: 'Upadek maszyny podczas monta\u017cu', effect: 'Zgniecenie os\u00f3b', defaultS: 3, defaultP: 2, actions: ['Plan monta\u017cu zatwierdzony przez in\u017cyniera', 'Kotwienie do pod\u0142ogi wg DTR'] },
      { id: 'pf09', element: 'Pierwsze uruchomienie maszyny', threat: 'Niezamierzone uruchomienie przy obecno\u015bci os\u00f3b', effect: 'Urazy r\u0105k', defaultS: 3, defaultP: 2, actions: ['Sprawdzenie os\u0142on przed uruchomieniem', 'Sygna\u0142 ostrzegawczy przed startem', 'Test kurtyn i czujnik\u00f3w'] },
      { id: 'pf10', element: 'Zmiana formatu opakowania', threat: 'Wci\u0105gni\u0119cie r\u0105k przy zmianie prowadnic', effect: 'Zmiażdżenie palc\u00f3w', defaultS: 3, defaultP: 2, actions: ['LOTO przy zmianie formatu', 'Procedura change-over', 'Szkolenie z zmiany formatu'] },
      { id: 'pf11', element: 'Zacie\u015bnienie / zaci\u0119cie opakowania', threat: 'R\u0119czne usuwanie zaci\u0119cia w ruchu', effect: 'Wci\u0105gni\u0119cie r\u0105k', defaultS: 4, defaultP: 3, actions: ['LOTO przed usuni\u0119ciem zaci\u0119cia', 'Zakaz r\u0119cznego usuwania w ruchu', 'Czujnik zaci\u0119cia z automatycznym zatrzymaniem'] },
      { id: 'pf12', element: 'Zgrzewanie \u2014 oparzenie pary', threat: 'Oparzenie par\u0105 wodna przy otwieraniu pokrywy zgrzewarki', effect: 'Oparzenia twarzy', defaultS: 3, defaultP: 2, actions: ['Deflektory pary', 'Tarcza ochronna twarzy', 'Procedura otwierania zgrzewarki'] },
      { id: 'pf13', element: 'Awaria grzałki zgrzewarki', threat: 'Przegrzanie \u2014 po\u017car folii', effect: 'Po\u017car maszyny', defaultS: 3, defaultP: 2, actions: ['Termostat z funkcj\u0105 bezpiecze\u0144stwa', 'Alarm temperatury', 'Kontrola grzałek co tydzie\u0144'] },
      { id: 'pf14', element: 'Czyszczenie maszyny / usuwanie resztek produktu', threat: 'Skaleczenie o ostre kraw\u0119dzie no\u017cy / prowadnic', effect: 'Rany ci\u0119te r\u0105k', defaultS: 3, defaultP: 3, actions: ['LOTO przed czyszczeniem', 'R\u0119kawice antyprzeci\u0119ciowe EN 388', 'Instrukcja czyszczenia'] },
      { id: 'pf15', element: 'Demonta\u017c maszyny pakuj\u0105cej', threat: 'Upadek element\u00f3w maszyny', effect: 'Urazy', defaultS: 3, defaultP: 1, actions: ['Plan demonta\u017cu zatwierdzony', 'Od\u0142\u0105czenie wszystkich medi\u00f3w', 'Min. 2 osoby'] },`);

// ===== PLASTICS-INJECTION: add in07-in20 after in06 =====
insertAfterById('in06', `
      { id: 'in07', element: 'Transport / instalacja wtryskiarki', threat: 'Upadek maszyny podczas transportu', effect: 'Zgniecenie os\u00f3b', defaultS: 4, defaultP: 2, actions: ['Plan transportu wg DTR', 'Kotwienie do pod\u0142ogi', 'Strefa wy\u0142\u0105czona podczas podnoszenia'] },
      { id: 'in08', element: 'Pierwsze uruchomienie wtryskiarki', threat: 'Wytrysk tworzywa przy b\u0142\u0119dnym ustawieniu ci\u015bnienia', effect: 'Oparzenie, iniekcja tworzywa', defaultS: 4, defaultP: 2, actions: ['Sprawdzenie parametr\u00f3w przed uruchomieniem', 'Protok\u00f3\u0142 pierwszego uruchomienia', 'Os\u0142ona dyszy'] },
      { id: 'in09', element: 'Zmiana formy wtryskowej', threat: 'Przygniecenie r\u0105k przez zamykaj\u0105c\u0105 si\u0119 form\u0119', effect: 'Zmiażdżenie r\u0105k \u2014 amputacja', defaultS: 4, defaultP: 2, actions: ['LOTO przy wymianie formy', 'Rygle mechaniczne formy', 'Narz\u0119dzia do monta\u017cu formy'] },
      { id: 'in10', element: 'Praca przy otwartej formie \u2014 serwis', threat: 'Zamkni\u0119cie formy przy obecno\u015bci r\u0105k serwisanta', effect: 'Amputacja', defaultS: 4, defaultP: 2, actions: ['Safety bar w formie', 'Czujnik obecno\u015bci w formie', 'LOTO przed wej\u015bciem w form\u0119'] },
      { id: 'in11', element: 'Przegrzanie cylindra plastyfikuj\u0105cego', threat: 'Wytrysk gorącego tworzywa przy przegrzaniu', effect: 'Ci\u0119\u017ckie oparzenia', defaultS: 4, defaultP: 1, actions: ['Termostat z alarmem', 'Kontrola temperatury co zmian\u0119', 'Os\u0142ona cylindra'] },
      { id: 'in12', element: 'Awaria uk\u0142adu hydraulicznego', threat: 'Wytrysk oleju hydraulicznego', effect: 'Po\u017car, iniekcja oleju', defaultS: 4, defaultP: 1, actions: ['Kontrola szczelno\u015bci co zmian\u0119', 'Serwis hydrauliki co 6 mies.', 'Ga\u015bnica CO\u2082 przy maszynie'] },
      { id: 'in13', element: 'Zanik zasilania wtryskiarki', threat: 'Zablokowanie formy w zamkni\u0119tej pozycji', effect: 'Utrata produktu, trudno\u015bci serwisowe', defaultS: 2, defaultP: 2, actions: ['Procedura r\u0119cznego otwierania formy', 'Zachowanie ci\u015bnienia hydraulicznego', 'UPS na sterownik'] },
      { id: 'in14', element: 'Czyszczenie cylindra / dyszy', threat: 'Oparzenie przy czyszczeniu gor\u0105cego cylindra', effect: 'Oparzenia II/III stopnia', defaultS: 3, defaultP: 3, actions: ['Sch\u0142odzenie do < 60\u00b0C przed czyszczeniem', 'R\u0119kawice termoodporne EN 407', 'Okulary ochronne EN 166'] },
      { id: 'in15', element: 'Demonta\u017c wtryskiarki', threat: 'Upadek ci\u0119\u017ckich element\u00f3w formy / maszyny', effect: 'Zgniecenie, \u015bmier\u0107', defaultS: 4, defaultP: 1, actions: ['Plan demonta\u017cu zatwierdzony przez in\u017cyniera', 'Od\u0142\u0105czenie wszystkich medi\u00f3w', 'Utylizacja olej\u00f3w i tworzywa'] },`);

// ===== CRANE-OVERHEAD: add cr07-cr20 after cr06 =====
insertAfterById('cr06', `
      { id: 'cr07', element: 'Transport / monta\u017c suwnicy', threat: 'Upadek element\u00f3w suwnicy podczas monta\u017cu', effect: 'Zgniecenie os\u00f3b', defaultS: 4, defaultP: 2, actions: ['Plan monta\u017cu zatwierdzony przez in\u017cyniera', 'Monta\u017c przez certyfikan\u0105 firm\u0119', 'Strefa wy\u0142\u0105czona podczas monta\u017cu'] },
      { id: 'cr08', element: 'Pierwsze uruchomienie suwnicy', threat: 'Niekontrolowany ruch przy rozruchu', effect: 'Uderzenie suwnicy w konstrukcj\u0119', effect: 'Uszkodzenie maszyny, urazy', defaultS: 3, defaultP: 2, actions: ['Test ruch\u00f3w bez \u0142adunku', 'Sprawdzenie wy\u0142\u0105cznik\u00f3w kr\u0105\u017ccowych', 'Protok\u00f3\u0142 pierwszego uruchomienia (UDT)'] },
      { id: 'cr09', element: 'Praca w warunkach wietrznych (suwnica hal zewn\u0119trznych)', threat: 'Ko\u0142ysanie \u0142adunku przy silnym wietrze', effect: 'Uderzenie \u0142adunkiem \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 2, actions: ['Zakaz pracy przy wietrze > 14 m/s', 'Anemometr z alarmem na suwnicy', 'Procedura kotwienia przy silnym wietrze'] },
      { id: 'cr10', element: 'Uderzenie \u0142adunku w maszyny / konstrukcje', threat: 'Rozbujanie \u0142adunku \u2014 uderzenie w s\u0105siednie urz\u0105dzenia', effect: 'Uszkodzenie maszyny, po\u017car', defaultS: 3, defaultP: 2, actions: ['Prowadniki kieruj\u0105ce \u0142adunek', 'Ograniczenie pr\u0119dko\u015bci jazdy przy ko\u0142ysaniu', 'Strefa bezpiecze\u0144stwa wolna od przeszk\u00f3d'] },
      { id: 'cr11', element: 'Awaria hamulca jazdy / podnoszenia', threat: 'Niezamierzone opuszczenie \u0142adunku', effect: 'Upadek \u0142adunku \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 1, actions: ['Kontrola hamulc\u00f3w przed ka\u017cd\u0105 zmian\u0105', 'Hamulec bezpiecze\u0144stwa na mechanizmie podnoszenia', 'Serwis hamulc\u00f3w co 6 mies.'] },
      { id: 'cr12', element: 'Praca na torach suwnicy (konserwacja)', threat: 'Uderzenie przez jad\u0105c\u0105 suwnic\u0119 podczas konserwacji', effect: 'Ci\u0119\u017ckie urazy \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 2, actions: ['Blokada jazdy suwnicy podczas prac na torach', 'Sygna\u0142 audio przed uruchomieniem', 'LOTO na sterowniku suwnicy'] },
      { id: 'cr13', element: 'Demonta\u017c suwnicy', threat: 'Upadek element\u00f3w suwnicy podczas demonta\u017cu', effect: 'Zgniecenie \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 1, actions: ['Plan demonta\u017cu zatwierdzony przez UDT', 'Strefa wy\u0142\u0105czona', 'Certyfikowana firma demonta\u017cowa'] },`);

// ===== AGRICULTURAL-COMBINE: add ag07-ag18 after ag06 =====
insertAfterById('ag06', `
      { id: 'ag07', element: 'Transport kombajnu na drodze', threat: 'Kolizja z pojazdem przy transporcie', effect: 'Wypadek drogowy \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 2, actions: ['O\u015bwietlenie i oznakowanie zgodne z PoRD', 'Pilot prowadz\u0105cy', 'Ograniczenie pr\u0119dko\u015bci 25 km/h'] },
      { id: 'ag08', element: 'Serwis kombinowej podczas zbior\u00f3w', threat: 'Pochwycenie przez mechanizm podczas serwisu w polu', effect: 'Amputacja \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 2, actions: ['LOTO przed serwisem', 'Zatrzymanie wszystkich mechanizm\u00f3w', 'Dwie osoby przy serwisie w polu'] },
      { id: 'ag09', element: 'Upadek z kombajnu podczas inspekcji', threat: 'Upadek z wysoko\u015bci przy wchodzeniu na kombajn', effect: 'Z\u0142amania, \u015bmier\u0107', defaultS: 3, defaultP: 2, actions: ['Drabinka z por\u0119czami', 'Szelki przy pracy na dachu', 'Zakaz wchodzenia w ruchu'] },
      { id: 'ag10', element: 'Py\u0142 ro\u015blinny / grzybowy podczas zbior\u00f3w', threat: 'Wdychanie py\u0142u organicznego przy zbiorach', effect: 'Pylica, reakcje alergiczne, p\u0142uco farmera', defaultS: 3, defaultP: 4, actions: ['Klimatyzacja i filtracja powietrza w kabinie', 'Maska FFP2 przy pracy poza kabin\u0105', 'Pomiar st\u0119\u017cenia py\u0142u organicznego'] },
      { id: 'ag11', element: 'Praca w upałach \u2014 stres termiczny', threat: 'Udar cieplny operatora w kabinie bez klimatyzacji', effect: 'Udar, omdlenie, \u015bmier\u0107', defaultS: 3, defaultP: 3, actions: ['Klimatyzacja kabiny obowi\u0105zkowa', 'Nawodnienie operatora (min. 500 ml/h)', 'Monitoring temperatury w kabinie'] },
      { id: 'ag12', element: 'Po\u017car kombajnu \u2014 suche resztki ro\u015blinne', threat: 'Zap\u0142on suchych resztek ro\u015blinnych od gor\u0105cego silnika', effect: 'Po\u017car pola i maszyny \u2014 \u015bmier\u0107', defaultS: 4, defaultP: 3, actions: ['Czyszczenie kombajnu co 4h podczas zbior\u00f3w', 'Ga\u015bnica proszkowa na kabinie', 'Czujnik dymu / temperatury silnika', 'Zakaz palenia na polu'] },`);

fs.writeFileSync('C:/Projects/riskpro/frontend/src/data/machines.ts', c, 'utf8');
console.log('\nFinal check:');
console.log('co12:', c.includes("id: 'co12'"));
console.log('cb15:', c.includes("id: 'cb15'"));
console.log('f15:', c.includes("id: 'f15'"));
console.log('pf15:', c.includes("id: 'pf15'"));
console.log('in15:', c.includes("id: 'in15'"));
console.log('cr13:', c.includes("id: 'cr13'"));
console.log('ag12:', c.includes("id: 'ag12'"));